[tool.poetry]
name = "kubeflow-torch-cpu"
version = "0.1.0"
description = "Kubeflow image for torch (CPU only)."
authors = ["Rene Jean Corneille <rene-jean.corneille@onclusive.com>"]

[tool.poetry.dependencies]
python = "3.8.16"
transformers = "4.36.0"
torch = "1.12.1"
numpy = "1.24.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
