[tool.poetry]
name = "IPTC ingest"
version = "0.1.0"
description = ""
authors = ["Ivan Okhotnikov <ivan.okhotnikov@onclusive.com>"]

[tool.poetry.dependencies]
python = "3.8.16"
urllib3 = "1.26"
core = {path = "../../../libs/core"}
apache-beam = {extras = ["dataframe"], version = "2.48.0"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
